### ISSUE TITLE
Typecasts not applied if there are no tag_name or date_format field configurations

### ISSUE THREAD

**Issue by nederdirk** [xavierlacot/sfDoctrineRestGeneratorPlugin#25]
Configurations like this:

``` yaml
      default:
        fields:                                # list here the fields.
          id: { type: int }
          company_id: {type: int}
```

won't apply the typecasting
